# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ejercicio
      POSTGRES_USER: arodgom

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
  
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example